"""Define helper constants for testing"""
HUB = "https://csdms.rc.colorado.edu"
REPO = "https://github.com/csdms/espin"
BRANCH = "main"
FILE = "lessons/jupyter/index.ipynb"
INTERFACE = "notebook"
VALID_LINK = "https://csdms.rc.colorado.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fcsdms%2Fespin&urlpath=tree%2Fespin%2Flessons%2Fjupyter%2Findex.ipynb&branch=main"
