name: Build/Test CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build and install package
        run: make install

      - name: Test
        run: |
          pip install pytest
          make test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint
        run: |
          pip install flake8
          make lint
